/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_test;
import java.util.*;
public class gui_test_2 extends javax.swing.JFrame {

    /**
     * Creates new form gui_test_2
     */
   double num_1;
   double num_2;
   String op,ans;
   double n,b;
    public gui_test_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButtonadd = new javax.swing.JButton();
        ButtonC = new javax.swing.JButton();
        jButtonmul = new javax.swing.JButton();
        jButtonsub = new javax.swing.JButton();
        jButtondiv = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        Button9 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        Button00 = new javax.swing.JButton();
        jButtondot = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        jButtonequls = new javax.swing.JButton();
        Buttonsin = new javax.swing.JButton();
        Buttoncos = new javax.swing.JButton();
        Buttontan = new javax.swing.JButton();
        Buttonround = new javax.swing.JButton();
        Buttonsqr = new javax.swing.JButton();
        Label1 = new javax.swing.JLabel();
        Buttonpow = new javax.swing.JButton();
        Buttonsqrt = new javax.swing.JButton();
        Buttonln = new javax.swing.JButton();
        Buttonsadd = new javax.swing.JButton();
        Buttonsign = new javax.swing.JButton();
        ButtonsinIn = new javax.swing.JButton();
        ButtoncosIn = new javax.swing.JButton();
        ButtontanIn = new javax.swing.JButton();
        ButtonE = new javax.swing.JButton();
        Buttonlog10 = new javax.swing.JButton();
        Buttonpi = new javax.swing.JButton();
        Buttonfact = new javax.swing.JButton();
        jButtoninv = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButtonadd.setBackground(new java.awt.Color(204, 204, 204));
        jButtonadd.setText("+");
        jButtonadd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonadd.setOpaque(false);
        jButtonadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //jButtonaddActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));

        ButtonC.setBackground(new java.awt.Color(204, 204, 204));
        ButtonC.setText("C");
        ButtonC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonC.setOpaque(false);
        ButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCActionPerformed(evt);
            }
        });

        jButtonmul.setBackground(new java.awt.Color(204, 204, 204));
        jButtonmul.setText("*");
        jButtonmul.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonmul.setOpaque(false);
        jButtonmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmulActionPerformed(evt);
            }
        });

        jButtonsub.setBackground(new java.awt.Color(204, 204, 204));
        jButtonsub.setText("-");
        jButtonsub.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonsub.setOpaque(false);
        jButtonsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsubActionPerformed(evt);
            }
        });

        jButtondiv.setBackground(new java.awt.Color(204, 204, 204));
        jButtondiv.setText("/");
        jButtondiv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtondiv.setOpaque(false);
        jButtondiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondivActionPerformed(evt);
            }
        });

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        Button9.setBackground(new java.awt.Color(204, 204, 204));
        Button9.setText("9");
        Button9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button9.setOpaque(false);
        Button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button9ActionPerformed(evt);
            }
        });

        Button7.setBackground(new java.awt.Color(204, 204, 204));
        Button7.setText("7");
        Button7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button7.setOpaque(false);
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        Button8.setBackground(new java.awt.Color(204, 204, 204));
        Button8.setText("8");
        Button8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button8.setOpaque(false);
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });

        Button4.setBackground(new java.awt.Color(204, 204, 204));
        Button4.setText("4");
        Button4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button4.setOpaque(false);
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });

        Button6.setBackground(new java.awt.Color(204, 204, 204));
        Button6.setText("6");
        Button6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button6.setOpaque(false);
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        Button5.setBackground(new java.awt.Color(204, 204, 204));
        Button5.setText("5");
        Button5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button5.setOpaque(false);
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });

        Button1.setBackground(new java.awt.Color(204, 204, 204));
        Button1.setText("1");
        Button1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button1.setOpaque(false);
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Button3.setBackground(new java.awt.Color(204, 204, 204));
        Button3.setText("3");
        Button3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button3.setOpaque(false);
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(204, 204, 204));
        jButton12.setText("2");
        jButton12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.setOpaque(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        Button00.setBackground(new java.awt.Color(204, 204, 204));
        Button00.setText("00");
        Button00.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button00.setOpaque(false);
        Button00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button00ActionPerformed(evt);
            }
        });

        jButtondot.setBackground(new java.awt.Color(204, 204, 204));
        jButtondot.setText(".");
        jButtondot.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtondot.setOpaque(false);
        jButtondot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondotActionPerformed(evt);
            }
        });

        Button0.setBackground(new java.awt.Color(204, 204, 204));
        Button0.setText("0");
        Button0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button0.setOpaque(false);
        Button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button0ActionPerformed(evt);
            }
        });

        jButtonequls.setBackground(new java.awt.Color(204, 204, 204));
        jButtonequls.setText("=");
        jButtonequls.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonequls.setOpaque(false);
        jButtonequls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonequlsActionPerformed(evt);
            }
        });

        Buttonsin.setBackground(new java.awt.Color(204, 204, 204));
        Buttonsin.setText("sin");
        Buttonsin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buttonsin.setOpaque(false);
        Buttonsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonsinActionPerformed(evt);
            }
        });

        Buttoncos.setBackground(new java.awt.Color(204, 204, 204));
        Buttoncos.setText("cos");
        Buttoncos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buttoncos.setOpaque(false);
        Buttoncos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtoncosActionPerformed(evt);
            }
        });

        Buttontan.setBackground(new java.awt.Color(204, 204, 204));
        Buttontan.setText("tan");
        Buttontan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buttontan.setOpaque(false);
        Buttontan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtontanActionPerformed(evt);
            }
        });

        Buttonround.setBackground(new java.awt.Color(204, 204, 204));
        Buttonround.setText("rnd");
        Buttonround.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buttonround.setOpaque(false);
        Buttonround.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonroundActionPerformed(evt);
            }
        });

        Buttonsqr.setBackground(new java.awt.Color(204, 204, 204));
        Buttonsqr.setText("x^2");
        Buttonsqr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buttonsqr.setOpaque(false);
        Buttonsqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonsqrActionPerformed(evt);
            }
        });

        Label1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Buttonpow.setBackground(new java.awt.Color(204, 204, 204));
        Buttonpow.setText("x^y");
        Buttonpow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buttonpow.setOpaque(false);
        Buttonpow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonpowActionPerformed(evt);
            }
        });

        Buttonsqrt.setBackground(new java.awt.Color(204, 204, 204));
        Buttonsqrt.setText("sqrt");
        Buttonsqrt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buttonsqrt.setOpaque(false);
        Buttonsqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonsqrtActionPerformed(evt);
            }
        });

        Buttonln.setBackground(new java.awt.Color(204, 204, 204));
        Buttonln.setText("ln");
        Buttonln.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buttonln.setOpaque(false);
        Buttonln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonlnActionPerformed(evt);
            }
        });

        Buttonsadd.setBackground(new java.awt.Color(204, 204, 204));
        Buttonsadd.setText("+");
        Buttonsadd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buttonsadd.setOpaque(false);
        Buttonsadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonsaddActionPerformed(evt);
            }
        });

        Buttonsign.setBackground(new java.awt.Color(204, 204, 204));
        Buttonsign.setText("+/-");
        Buttonsign.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buttonsign.setOpaque(false);
        Buttonsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonsignActionPerformed(evt);
            }
        });

        ButtonsinIn.setBackground(new java.awt.Color(204, 204, 204));
        ButtonsinIn.setText("sinIn");
        ButtonsinIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonsinIn.setOpaque(false);
        ButtonsinIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonsinInActionPerformed(evt);
            }
        });

        ButtoncosIn.setBackground(new java.awt.Color(204, 204, 204));
        ButtoncosIn.setText("cosIn");
        ButtoncosIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtoncosIn.setOpaque(false);
        ButtoncosIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtoncosInActionPerformed(evt);
            }
        });

        ButtontanIn.setBackground(new java.awt.Color(204, 204, 204));
        ButtontanIn.setText("tanIn");
        ButtontanIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtontanIn.setOpaque(false);
        ButtontanIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtontanInActionPerformed(evt);
            }
        });

        ButtonE.setBackground(new java.awt.Color(204, 204, 204));
        ButtonE.setText("e");
        ButtonE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonE.setOpaque(false);
        ButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEActionPerformed(evt);
            }
        });

        Buttonlog10.setBackground(new java.awt.Color(204, 204, 204));
        Buttonlog10.setText("log");
        Buttonlog10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buttonlog10.setOpaque(false);
        Buttonlog10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttonlog10ActionPerformed(evt);
            }
        });

        Buttonpi.setBackground(new java.awt.Color(204, 204, 204));
        Buttonpi.setText("pi");
        Buttonpi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buttonpi.setOpaque(false);
        Buttonpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonpiActionPerformed(evt);
            }
        });

        Buttonfact.setBackground(new java.awt.Color(204, 204, 204));
        Buttonfact.setText("n!");
        Buttonfact.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Buttonfact.setOpaque(false);
        Buttonfact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonfactActionPerformed(evt);
            }
        });

        jButtoninv.setBackground(new java.awt.Color(204, 204, 204));
        jButtoninv.setText("IN");
        jButtoninv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtoninv.setOpaque(false);
        jButtoninv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoninvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button00, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Buttonsin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buttoncos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buttontan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonsub, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buttonsign, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtondot, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Buttonpow, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Buttonsqr, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Buttonsqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonmul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtondiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Buttonsadd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ButtontanIn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Buttonfact, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ButtoncosIn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Buttonpi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ButtonsinIn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Buttonlog10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Buttonround, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Buttonln, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtoninv, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonequls, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(Label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button00, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Buttoncos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Buttonsin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Buttontan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonsub, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Buttonsign, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Buttonpow, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Buttonsqr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Buttonsqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Buttonsadd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonsinIn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Buttonlog10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtondiv, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtoncosIn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Buttonpi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonmul, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtontanIn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Buttonfact, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtondot, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buttonround, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buttonln, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonequls, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtoninv, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCActionPerformed
  jTextField1.setText("");
        
    }//GEN-LAST:event_ButtonCActionPerformed

    private void Button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button9ActionPerformed
      
        jTextField1.setText(jTextField1.getText()+"9");
    }//GEN-LAST:event_Button9ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
         
              jTextField1.setText(jTextField1.getText()+"4");
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
      
        jTextField1.setText(jTextField1.getText()+"1");
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button00ActionPerformed
      
        jTextField1.setText(jTextField1.getText()+"00");
    }//GEN-LAST:event_Button00ActionPerformed

    private void jButtonsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsubActionPerformed
           num_1 = Double.parseDouble(jTextField1.getText());
        op ="-";        
        jTextField1.setText("");
      Label1.setText(num_1+" - ");
    }//GEN-LAST:event_jButtonsubActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
       
        jTextField1.setText(jTextField1.getText()+"8");
    }//GEN-LAST:event_Button8ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
      
        jTextField1.setText(jTextField1.getText()+"7");
    }//GEN-LAST:event_Button7ActionPerformed

    private void jButtonmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmulActionPerformed
         num_1 = Double.parseDouble(jTextField1.getText());
        op ="*";        
        jTextField1.setText("");
        Label1.setText(num_1+" * ");
    }//GEN-LAST:event_jButtonmulActionPerformed

    private void jButtondivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondivActionPerformed
          num_1 = Double.parseDouble(jTextField1.getText());
        op ="/";        
        jTextField1.setText("");
        Label1.setText(num_1+" / ");
    }//GEN-LAST:event_jButtondivActionPerformed
/*
    private void jButtonaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddActionPerformed
     /*   num_1 = Double.parseDouble(jTextField1.getText());
               op ="+";  
       jTextField1.setText("");
        Label1.setText(num_1+" + ");
        
    }//GEN-LAST:event_jButtonaddActionPerformed
*/
    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
      
        jTextField1.setText(jTextField1.getText()+"5");
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        
      
         jTextField1.setText(jTextField1.getText()+"6");
    }//GEN-LAST:event_Button6ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
      
          jTextField1.setText(jTextField1.getText()+"2");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
       
        jTextField1.setText(jTextField1.getText()+"3");
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button0ActionPerformed
      
         jTextField1.setText(jTextField1.getText()+"0");
    }//GEN-LAST:event_Button0ActionPerformed

    private void jButtondotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondotActionPerformed
                   jTextField1.setText(jTextField1.getText()+".");
    }//GEN-LAST:event_jButtondotActionPerformed

    private void ButtonsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonsinActionPerformed
             num_1=Double.parseDouble(jTextField1.getText());
     // op="sin";
      Label1.setText("sin("+num_1+")");
      b=Math.toRadians(num_1);
          n=Math.sin(b);
         ans=String.valueOf(n);
            jTextField1.setText(ans);
                 
    }//GEN-LAST:event_ButtonsinActionPerformed

    private void ButtoncosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtoncosActionPerformed
      num_1=Double.parseDouble(jTextField1.getText());
      op="cos";
      Label1.setText("cos("+num_1+")");
        b=Math.toRadians(num_1);
          n=Math.cos(b);
         ans=String.valueOf(n);
            jTextField1.setText(ans);
    }//GEN-LAST:event_ButtoncosActionPerformed

    private void ButtontanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtontanActionPerformed
       num_1=Double.parseDouble(jTextField1.getText());
      op="tan";
      Label1.setText("tan("+num_1+")");
        b=Math.toRadians(num_1);
          n=Math.tan(b);
         ans=String.valueOf(n);
            jTextField1.setText(ans);
    }//GEN-LAST:event_ButtontanActionPerformed

    private void ButtonroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonroundActionPerformed
       num_1=Double.parseDouble(jTextField1.getText()); 
          n=Math.round(num_1);
         ans=String.valueOf(n);
            jTextField1.setText(ans);
        
    }//GEN-LAST:event_ButtonroundActionPerformed

    private void ButtonsqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonsqrActionPerformed
         num_1=Double.parseDouble(jTextField1.getText());
    //  op="sqr";
       n=Math.pow(num_1,2);
         ans=String.valueOf(n);
            jTextField1.setText(ans);
    }//GEN-LAST:event_ButtonsqrActionPerformed

    private void jButtonequlsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonequlsActionPerformed
     //   String ans;
      
       num_2=Double.valueOf(jTextField1.getText());
     //  Label1.setText(num_2);
     switch(op){   
         case "+":
            n=num_1+num_2;
            ans=String.valueOf(n);
            jTextField1.setText(ans);
         Label1.setText(ans);
         break;
        
        case "-":
            n=num_1-num_2;
           ans=String.valueOf(n);
            jTextField1.setText(ans);
            Label1.setText(ans);
            break;
        
        case "*":
            n=num_1*num_2;
          ans=String.valueOf(n);
            jTextField1.setText(ans);
            Label1.setText(ans);
            break;
        
         case "/":
            n=num_1/num_2;
        ans=String.valueOf(n);
            jTextField1.setText(ans);
            Label1.setText(ans);
        break;
                    
            case "pow":
           n=Math.pow(num_1,num_2);
         ans=String.valueOf(n);
            jTextField1.setText(ans);
            Label1.setText(ans);
            break;
            
           
         }
     
     
     
     
     
     
    }//GEN-LAST:event_jButtonequlsActionPerformed

    private void ButtonpowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonpowActionPerformed
        num_1=Double.parseDouble(jTextField1.getText());
        op="pow";
        jTextField1.setText("");
        Label1.setText(num_1+"^");
    }//GEN-LAST:event_ButtonpowActionPerformed

    private void ButtonsqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonsqrtActionPerformed
        num_1=Double.parseDouble(jTextField1.getText());
       n=Math.sqrt(num_1);
      ans=String.valueOf(n);
      jTextField1.setText(ans);
    }//GEN-LAST:event_ButtonsqrtActionPerformed

    private void ButtonlnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonlnActionPerformed
       num_1=Double.parseDouble(jTextField1.getText());
        n=Math.log(num_1);
        Label1.setText("ln("+num_1+")");
         ans=String.valueOf(n);
            jTextField1.setText(ans);
            
    }//GEN-LAST:event_ButtonlnActionPerformed

    private void ButtonsaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonsaddActionPerformed
        num_1 = Double.parseDouble(jTextField1.getText());
               op ="+";  
       jTextField1.setText("");
        Label1.setText(num_1+" + ");
    }//GEN-LAST:event_ButtonsaddActionPerformed

    private void ButtonsignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonsignActionPerformed
      num_1 =Double.parseDouble(jTextField1.getText());

num_1*=-1;
ans=String.valueOf(num_1);
jTextField1.setText(ans);
    }//GEN-LAST:event_ButtonsignActionPerformed

    private void ButtonsinInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonsinInActionPerformed
      num_1=Double.parseDouble(jTextField1.getText());
      Label1.setText("sinIn("+num_1+")");  
       n=Math.asin(num_1);
       b = (n*180)/Math.PI;
        ans=String.valueOf(b);
            jTextField1.setText(ans);
    
     
    }//GEN-LAST:event_ButtonsinInActionPerformed

    private void ButtoncosInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtoncosInActionPerformed
       num_1=Double.parseDouble(jTextField1.getText());
      Label1.setText("cosIn("+num_1+")");  
       n=Math.acos(num_1);
       b = (n*180)/Math.PI;
        ans=String.valueOf(b);
            jTextField1.setText(ans);
         
    }//GEN-LAST:event_ButtoncosInActionPerformed

    private void ButtontanInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtontanInActionPerformed
       num_1=Double.parseDouble(jTextField1.getText());
      Label1.setText("tanIn("+num_1+")");  
       n=Math.atan(num_1);
       b = (n*180)/Math.PI;
        ans=String.valueOf(b);
            jTextField1.setText(ans);
    }//GEN-LAST:event_ButtontanInActionPerformed

    private void ButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEActionPerformed
     num_1=Double.parseDouble(jTextField1.getText());
      Label1.setText("e("+num_1+")");
      n=Math.exp(num_1);
      ans=String.valueOf(n);
      jTextField1.setText(ans);
      Label1.setText(ans);
      
      
    }//GEN-LAST:event_ButtonEActionPerformed

    private void Buttonlog10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttonlog10ActionPerformed

 num_1=Double.parseDouble(jTextField1.getText());
      Label1.setText("log("+num_1+")");
      n=Math.log10(num_1);
      ans=String.valueOf(n);
      jTextField1.setText(ans);
      Label1.setText(ans);
    }//GEN-LAST:event_Buttonlog10ActionPerformed

    private void ButtonfactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonfactActionPerformed
      
 int c;
        num_1=Double.parseDouble(jTextField1.getText());
        c=(int)num_1;
        n=(double)c;
        if(num_1==n){
         Label1.setText(num_1+"!");
        for(int a=c-1;a>=1;a--){
            c*=a;}       
        ans=String.valueOf(c);
        jTextField1.setText(ans);
      Label1.setText(ans);}
        else{
            jTextField1.setText("Math Error");
      Label1.setText("Math Error");}
            
      
        
        
    }//GEN-LAST:event_ButtonfactActionPerformed

    private void ButtonpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonpiActionPerformed
        jTextField1.setText(jTextField1.getText()+Math.PI);
    }//GEN-LAST:event_ButtonpiActionPerformed

    private void jButtoninvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoninvActionPerformed
num_1=Double.parseDouble(jTextField1.getText());
n=1/num_1;
ans=String.valueOf(n);
jTextField1.setText(ans);
      Label1.setText(ans);

    }//GEN-LAST:event_jButtoninvActionPerformed
 
          
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui_test_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui_test_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui_test_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui_test_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui_test_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button00;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton ButtonC;
    private javax.swing.JButton ButtonE;
    private javax.swing.JButton Buttoncos;
    private javax.swing.JButton ButtoncosIn;
    private javax.swing.JButton Buttonfact;
    private javax.swing.JButton Buttonln;
    private javax.swing.JButton Buttonlog10;
    private javax.swing.JButton Buttonpi;
    private javax.swing.JButton Buttonpow;
    private javax.swing.JButton Buttonround;
    private javax.swing.JButton Buttonsadd;
    private javax.swing.JButton Buttonsign;
    private javax.swing.JButton Buttonsin;
    private javax.swing.JButton ButtonsinIn;
    private javax.swing.JButton Buttonsqr;
    private javax.swing.JButton Buttonsqrt;
    private javax.swing.JButton Buttontan;
    private javax.swing.JButton ButtontanIn;
    private javax.swing.JLabel Label1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButtonadd;
    private javax.swing.JButton jButtondiv;
    private javax.swing.JButton jButtondot;
    private javax.swing.JButton jButtonequls;
    private javax.swing.JButton jButtoninv;
    private javax.swing.JButton jButtonmul;
    private javax.swing.JButton jButtonsub;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void JTextField(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
